### PR TITLE
removed some duplicate dependencies (for lisp ontology) and minor fix…

### PR DESCRIPTION
**Pull request by jvansoest**
removed some duplicate dependencies (for lisp ontology) and minor fixes (for lisp ontology)

### CODE REVIEW

**Comment by mpomarlan** [comment]
What is the failed-object class intended to do? It has a lot of superclasses ...

**Comment by jvansoest** [comment]
It is used solely for evaluation and benchmarking in case anything goes wrong

**Comment by mpomarlan** [comment]
Ok. What about its superclasses however, to me it looks strange that it has to be all of those things at once.

**Comment by jvansoest** [comment]
Yes, it needs all those so that it can still match on all types when continuing the IRL execution

**Pull request merged**
